# Numpy Library - For Numeric Calculations

In [ ]:
#If numpy is not installed on your system, then use the code below to install it
#pip install numpy

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import numpy as np
#np.array
#from numpy import array

In [ ]:
#1 Dimensional Array
a=np.array([4,7,8,5,4,5,5,9])
a

array([4, 7, 8, 5, 4, 5, 5, 9])

In [ ]:
#It is an ndarray, i.e. n-dimensional array
type(a)

numpy.ndarray

In [ ]:
a.shape

(8,)

In [ ]:
#2 Dimensional Array
a=np.array([[5,2],[3,7],[9,6]])
a

array([[5, 2],
       [3, 7],
       [9, 6]])

In [ ]:
#Last value in this tuple is always number of columns
#Last but second value in this tuple is always number of rows
a.shape
#In this case there are 3 rows and 2 columns

(3, 2)

In [ ]:
#3 Dimensional Array
a=np.array([[[1,2],[3,2],[5,6]],
           [[5,2],[3,4],[5,3]],
           [[8,2],[7,4],[5,4]],
           [[1,4],[5,4],[7,6]]])
a

array([[[1, 2],
        [3, 2],
        [5, 6]],

       [[5, 2],
        [3, 4],
        [5, 3]],

       [[8, 2],
        [7, 4],
        [5, 4]],

       [[1, 4],
        [5, 4],
        [7, 6]]])

In [ ]:
a.shape

(4, 3, 2)

In [ ]:
#3 Dimensional Array
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,19,10]],
            [[1,2,8,4],[4,5,6,7],[7,7,9,10]],
            [[1,2,3,4],[4,6,9,7],[7,8,9,10]],
            [[1,3,3,4],[4,5,6,7],[7,8,11,10]],
            [[5,2,3,4],[4,11,6,8],[7,13,4,12]]])
a

In [ ]:
a.shape

In [ ]:
a[4,1,1]

In [ ]:
#2 Dimensional Array with unequal sub-arrays
a=np.array([[1,2],[3,4,6],[5,6]])
a

In [ ]:
a.shape

In [ ]:
c=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
            [[13,12,13,14],[15,16,17,18],[19,10,11,12]],
            [[11,12,13,14],[15,16,17,18],[19,10,11,12]]])
c

In [ ]:
#4 Dimensional Array
a=np.array([[[[1,2,3,4],[4,5,6,7],[7,8,9,10]],
             [[1,2,3,4],[4,5,6,7],[7,8,9,10]]],
            [[[1,2,8,4],[4,5,6,7],[7,8,6,10]],
             [[1,2,8,4],[4,5,6,7],[7,8,9,10]]],
            [[[1,2,3,4],[4,6,9,7],[7,8,9,10]],
             [[1,2,12,4],[4,6,9,7],[7,8,19,10]]],
            [[[1,3,3,4],[4,5,6,7],[7,8,11,10]],
             [[1,3,3,4],[4,5,6,7],[7,8,9,10]]],
            [[[5,2,3,4],[4,11,6,7],[7,8,4,10]],
             [[5,2,3,4],[4,11,6,7],[7,18,4,10]]]])
a

array([[[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10]],

        [[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10]]],


       [[[ 1,  2,  8,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  6, 10]],

        [[ 1,  2,  8,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4],
         [ 4,  6,  9,  7],
         [ 7,  8,  9, 10]],

        [[ 1,  2, 12,  4],
         [ 4,  6,  9,  7],
         [ 7,  8, 19, 10]]],


       [[[ 1,  3,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8, 11, 10]],

        [[ 1,  3,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10]]],


       [[[ 5,  2,  3,  4],
         [ 4, 11,  6,  7],
         [ 7,  8,  4, 10]],

        [[ 5,  2,  3,  4],
         [ 4, 11,  6,  7],
         [ 7, 18,  4, 10]]]])

In [ ]:
a.shape

(5, 2, 3, 4)

In [ ]:
#5-dimensional
a=np.array([[[[[1,2],[3,4],[1,2],[3,4]],[[1,2],[3,4],[1,2],[3,4]]],
             [[[1,2],[3,4],[1,2],[3,4]],[[1,2],[3,4],[1,2],[3,4]]],
             [[[1,2],[3,4],[1,2],[3,4]],[[1,2],[3,4],[1,2],[3,4]]]],
            [[[[1,2],[3,4],[1,2],[3,4]],[[1,2],[3,4],[1,2],[3,4]]],
             [[[1,2],[3,4],[1,2],[3,4]],[[1,2],[3,4],[1,2],[3,4]]],
             [[[1,2],[3,4],[1,2],[8,4]],[[1,2],[3,1],[1,2],[3,4]]]],
            [[[[1,2],[3,4],[1,2],[3,4]],[[1,2],[3,4],[4,2],[3,4]]],
             [[[1,2],[3,4],[1,5],[3,4]],[[1,2],[3,4],[1,2],[7,4]]],
             [[[1,2],[3,4],[1,2],[3,4]],[[1,2],[3,4],[1,4],[3,4]]]]])
a

In [ ]:
a.shape

In [ ]:
a=np.array([[1,2,8,6],[9,10,3,4],[5,6,6,2]])
a

array([[ 1,  2,  8,  6],
       [ 9, 10,  3,  4],
       [ 5,  6,  6,  2]])

In [ ]:
#The array 'a' has 3 rows & 4 columns
a.shape

(3, 4)

In [ ]:
#Please remember Python indexation starts from 0
#We are accessing the element at row index 1 and column index 2
a[1,2]

3

In [ ]:
#To access element at row 2 & column 3
a[2,3]

2

In [ ]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],
            [21,22,23,24,25]])
a

In [ ]:
a=np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
a=np.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
a=np.arange(1,60,3)
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58])

In [ ]:
a=np.array([np.arange(1,6),np.arange(6,11),np.arange(11,16),np.arange(16,21),
            np.arange(21,26)])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
a=np.arange(1,27).reshape(5,5)
a

ValueError: ignored

In [ ]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#3-D Array
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a

In [ ]:
a=np.arange(5)
a

In [ ]:
a=np.arange(8)
a

In [ ]:
#5,6,7,8,9,10,11
a=np.arange(5,12)
a

In [ ]:
a=np.arange(3,50,5)
a

In [ ]:
#-1,0,1
a=np.arange(-1,1,9)
a

In [ ]:
#19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1
a=np.arange(16,2,2)
a

In [ ]:
#16,15,14....6,5,4,3,2,1
a=np.arange(16,2,-2)
a

In [ ]:
# 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
a=np.arange(2,16,2)
a

In [ ]:
#16,15,14....6,5,4,3,2,1,0,-1,-2,-3
np.arange(16,1,-2)

In [ ]:
np.arange(16,0,-1)

In [ ]:
np.arange(16,-1,-1)

In [ ]:
np.arange(16,-5,-1)

In [ ]:
#16,15,14,13,12...6,5,4,3,2,1
a=np.arange(16,12,-2)
a

In [ ]:
a=np.arange(1,21)
print(a)
a**3

In [ ]:
a=np.arange(0,341,17)
a

Create a dataframe using numpy array structure, with 3 columns,

1st col- squares of 1st 10 natural numbers

2nd col- cubes of 1st 10 natural numbers

3rd col- mean of the 1st 2 columns

In [ ]:
import pandas as pd
natural_no=pd.DataFrame(columns=['col1','col2','col3'])
natural_no
col1= np.arange(1,11)
a=col1**2
print(a)
col2=np.arange(1,11)
b=col2**3
print(b)
col3=(a+b)/2
col3
natural_no['col1']=pd.Series(a)
natural_no['col2']=pd.Series(b)
natural_no['col3']=pd.Series(col3)
natural_no

In [ ]:
import pandas as pd
natural_no=pd.DataFrame(columns=['col1','col2','col3'])
natural_no['col1']=pd.Series((np.arange(1,11))**2)
natural_no['col2']=pd.Series(np.arange(1,11)**3)
natural_no['col3']=natural_no.iloc[:,[0,1]].mean(axis=1)
natural_no

In [ ]:
import pandas as pd
a1=pd.DataFrame(columns=['a','b','c'])
a1['a']=pd.Series((np.arange(1,11)**2))
a1['b']=pd.Series((np.arange(1,11)**3))
a1['c']=a1.iloc[:,[0,1]].mean(axis=1)
a1

In [ ]:
d1= [1,2,3,4,5,6,7,8,9,10]
a=[number**2 for number in d1]
b=[number**3 for number in d1]
c=np.mean(a and b)
d=np.array([[a],[b],[c]])
d

In [ ]:
a=np.square(np.arange(1,11))
a

In [ ]:
a1=np.arange(1,11)
a1=a1*a1
a2=np.arange(1,11)
a2=a2**3
a3=(a1+a2)/2
a3
import pandas as pd
df=pd.DataFrame(columns=['a1','a2','a3'])
df['a1']=pd.Series(a1)
df['a2']=pd.Series(a2)
df['a3']=pd.Series(a3)
df

In [ ]:
import pandas as pd
df=pd.DataFrame(columns=['Squares', 'Cubes', 'Mean'])
df['Squares']=pd.Series(np.arange(1,11)**2)
df['Cubes']=pd.Series(np.arange(1,11)**3)
df['Mean']=pd.Series(((np.arange(1,11)**2)+(np.arange(1,11)**3))/2)
df


In [ ]:
import pandas as pd
a=np.arange(1,11)
print(a)
b=[]
for i in a:
    b.append(i*i)
print(b)
x=pd.Series(b)
x

In [ ]:
a=np.arange(1,11)
b=[]
for i in a:
    b.append(i*i*i)
y=pd.Series(b)
y

In [ ]:
z=(x+y)/2
z

In [ ]:
frame={'x':x, 'y':y, "z":z }
result=pd.DataFrame(frame)
result

In [ ]:
a=([[0,11]])
for a in range(1,11):
    print(a*a*a, end= ",")

In [ ]:
a = np.arange(0,11)
a*a*a

In [ ]:
#linspace - creates equal intervals between a defined range
a=np.linspace(2,16,6)
a
#2 , , , , , 16

array([ 2. ,  4.8,  7.6, 10.4, 13.2, 16. ])

In [ ]:
for i in range(len(a)-1):   #i=0,1,2,3,4
  d=a[i+1] - a[i]
  print(d)

2.8
2.8
2.799999999999999
2.8000000000000007
2.8000000000000007


In [ ]:
a=np.linspace(5,60,15)
a

array([ 5.        ,  8.92857143, 12.85714286, 16.78571429, 20.71428571,
       24.64285714, 28.57142857, 32.5       , 36.42857143, 40.35714286,
       44.28571429, 48.21428571, 52.14285714, 56.07142857, 60.        ])

In [ ]:
len(a)

15

In [ ]:
for i in range(len(a)-1):  #i=0,1,2,3....13
  d=a[i+1] - a[i]
  print(d)

3.928571428571429
3.928571428571429
3.928571428571427
3.9285714285714306
3.928571428571427
3.928571428571427
3.9285714285714306
3.9285714285714306
3.9285714285714235
3.9285714285714306
3.9285714285714306
3.9285714285714235
3.9285714285714306
3.9285714285714306


In [ ]:
# To find the difference between every consecutive element in an array.
print('"i" will take all the possible values as shown in the list:',list(range(0,len(a)-1)))
for i in range(len(a)-1):
  d=a[i+1] - a[i]
  print(d)

In [ ]:
27**(1/3)

In [ ]:
print("4.8 - 2 is", 4.8 - 2)
print("7.6 - 4.8 is", 7.6 - 4.8)
print("10.4 - 7.6 is", 10.4 - 7.6)
print("13.2 - 10.4 is", 13.2 - 10.4)
print("16 - 13.2 is", 16 - 13.2)

In [ ]:
a=np.linspace(2,20,9)
print(a)
j=0
for i in a:
    print((i-j)==(i+1)-(j+1))

# (2 - 0) == (2 + 1) - (0 + 1)     2 == 3-1
# (4.25 - 0) == (4.25 + 1) - (0 + 1) == 4.25

In [ ]:
for i in range(10):
    for j in range(10):
      print(i,j)

In [ ]:
arr=np.linspace(2,20,9)
print(arr)
for i in range(1,10):    #0,1,2,3,4,5,6,7,8,9
    for j in range(8): #0,1,2,3,4,5,6,7,8,9
        if i == j+1:
          print(arr[j]-arr[i])

In [ ]:
a=np.linspace(2,20,9)
print(a)
for i in range(len(a)-1):   #0,1,2,3,4,5,6,7
    print(a[i+1],'-',a[i],'=',a[i+1]-a[i])

In [ ]:
a=np.linspace(2,20,9)
a

In [ ]:
len(a)

In [ ]:
list(range(len(a)-1))

In [ ]:
for i in (range(len(a) - 1)):
    print(i)
    print(a[i+1], "-" , a[i] , "is" , a[i+1] - a[i])

In [ ]:
j = 0
for item in a:
    j = j+1
    i = a[j]-item
    print(i)

In [ ]:
np.linspace(2,16,3)

In [ ]:
a=np.linspace(2,20,9)
a
#2..........20

In [ ]:
len(a)-1

In [ ]:
for i in range(len(a)-1):   #0,1,2,3,4,5,6,7
    print(a[i+1]-a[i])      #i=2   i+1=3

In [ ]:
b=np.zeros(8)
b

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
print("This is a 2 dimensional zero array")
print(np.zeros((3,3)))
print("------------------------------------")
print("This is a 3 dimensional zero array")
print(np.zeros((3,3,5)))
print("------------------------------------")
print("This is a 4 dimensional zero array")
print(np.zeros((2,3,3,5)))
print("------------------------------------")

This is a 2 dimensional zero array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------
This is a 3 dimensional zero array
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
------------------------------------
This is a 4 dimensional zero array
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
------------------------------------


In [ ]:
#5 is the number of times array is repeated
#3 is the number of rows per array
#4 is the number of columns per array
c=np.zeros((2,5,5,3,4))
c

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0.,

In [ ]:
2*3*4*2*3*4

576

In [ ]:
#Create an array of dimensions 2,3,4,2,3,4
#2*3*4*2*3*4 = 576
#So we need 576 elements to create such an array through reshape function
np.arange(576).reshape(2,3,4,2,3,4)

array([[[[[[  0,   1,   2,   3],
           [  4,   5,   6,   7],
           [  8,   9,  10,  11]],

          [[ 12,  13,  14,  15],
           [ 16,  17,  18,  19],
           [ 20,  21,  22,  23]]],


         [[[ 24,  25,  26,  27],
           [ 28,  29,  30,  31],
           [ 32,  33,  34,  35]],

          [[ 36,  37,  38,  39],
           [ 40,  41,  42,  43],
           [ 44,  45,  46,  47]]],


         [[[ 48,  49,  50,  51],
           [ 52,  53,  54,  55],
           [ 56,  57,  58,  59]],

          [[ 60,  61,  62,  63],
           [ 64,  65,  66,  67],
           [ 68,  69,  70,  71]]],


         [[[ 72,  73,  74,  75],
           [ 76,  77,  78,  79],
           [ 80,  81,  82,  83]],

          [[ 84,  85,  86,  87],
           [ 88,  89,  90,  91],
           [ 92,  93,  94,  95]]]],



        [[[[ 96,  97,  98,  99],
           [100, 101, 102, 103],
           [104, 105, 106, 107]],

          [[108, 109, 110, 111],
           [112, 113, 114, 115],
           [116

In [ ]:
a=np.array([[8,7,5],[10,3,9],[2,8,4]])
a

array([[ 8,  7,  5],
       [10,  3,  9],
       [ 2,  8,  4]])

In [ ]:
#To access a particular column in array
a[:,1]

array([7, 3, 8])

In [ ]:
#To access a particular row in array
a[2,:]

array([2, 8, 4])

In [ ]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#To access multiple rows from an array,
# i.e. row at index 0,2,4 in the command below
print(a)
a[[0,2,4],:]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [ ]:
#To access columns at index 0,2,4 across all rows
print(a)
a[:,[0,2,4]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [ ]:
#To access columns at index 0 & 4
a[:,[0,4]]

In [ ]:
a

In [ ]:
#The element at (row 1 & column 2) AND (row 3 & column 4) will be selected
a[[1,3],[2,4]]

In [ ]:
#The element at row index 2 & column index 3
a[2,3]

In [ ]:
#To access columns from index 0 to index 3
a[:,0:4]

In [ ]:
a[1:4,:]

In [ ]:
#Axis 0 = Column-wise
#Axis 1 = Row-wise

In [ ]:
a=np.random.randint(0,10,25).reshape(5,5)
a

array([[5, 3, 3, 2, 6],
       [7, 5, 8, 8, 4],
       [2, 1, 3, 2, 5],
       [8, 6, 1, 9, 9],
       [6, 2, 1, 8, 0]])

In [ ]:
#Column-wise and Row-wise minimum value
print('Column-wise minimum values are',a.min(axis=0))
print('Row-wise minimum values are',a.min(axis=1))

Column-wise minimum values are [2 1 1 2 0]
Row-wise minimum values are [2 4 1 1 0]


In [ ]:
#Column-wise and Row-wise maximum value
print('Column-wise maximum values are',a.max(axis=0))
print('Row-wise maximum values are',a.max(axis=1))

Column-wise maximum values are [8 6 8 9 9]
Row-wise maximum values are [6 8 5 9 8]


In [ ]:
#Column-wise summation
print(a)
a.sum(axis=0)

[[5 3 3 2 6]
 [7 5 8 8 4]
 [2 1 3 2 5]
 [8 6 1 9 9]
 [6 2 1 8 0]]


array([28, 17, 16, 29, 24])

In [ ]:
np.median(a,axis=0)

In [ ]:
import numpy as np
a = np.array([[[2,3,3,4],[3,4,4,4],[5,6,10,3],[7,8,4,4]],
              [[2,3,3,4],[3,4,5,4],[5,6,2,3],[7,6,4,4]],
              [[22,3,23,4],[3,4,14,4],[5,6,9,3],[7,8,4,12]],
              [[2,43,3,4],[3,8,4,4],[5,6,2,11],[7,2,4,13]]])
print(a)

In [ ]:
for i in a:
    print(i.max(axis=0))

In [ ]:
for i in a:
    print(i.sum(axis=0))

In [ ]:
a=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
a

In [ ]:
#Column-wise sum values
a.sum(axis=0)

In [ ]:
# Row-wise sum values
a.sum(axis=1)

In [ ]:
#Square Root the entire array
a=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(a)
np.sqrt(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [ ]:
#To find square root of a specific element, e.g. 4
print(a)
print(a[1,0])
np.sqrt(a[1,0])

In [ ]:
#Square root of 10 from array 'a'
np.sqrt(a[2,2])

In [ ]:
#To find square root of entire row at index 2
print(a)
np.sqrt(a[2,:])

In [ ]:
#To find square root of entire column at index 1
print(a)
np.sqrt(a[:,1])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.log(a)

array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

Log of a number to a base defined will give us the number to which the base must be raised to get the value for which we are finding the log

Log of 'a' to the base 'b' will give us the power of 'b', for which the result will be 'a'
log of 4 to the base 2

### Natural log

log of 5 will give us the power of e (constant) which gives the output as 5.

e=2.718

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)
np.square(a)

[[2 3 3 4]
 [3 4 4 4]
 [5 6 2 3]
 [7 8 4 4]]


array([[ 4,  9,  9, 16],
       [ 9, 16, 16, 16],
       [25, 36,  4,  9],
       [49, 64, 16, 16]])

In [ ]:
#Cummulative sum
print(a)
np.cumsum(a)

[[2 3 3 4]
 [3 4 4 4]
 [5 6 2 3]
 [7 8 4 4]]


array([ 2,  5,  8, 12, 15, 19, 23, 27, 32, 38, 40, 43, 50, 58, 62, 66])

In [ ]:
#Columnwise cummulative sum
print(a)
np.cumsum(a,axis=0)

[[2 3 3 4]
 [3 4 4 4]
 [5 6 2 3]
 [7 8 4 4]]


array([[ 2,  3,  3,  4],
       [ 5,  7,  7,  8],
       [10, 13,  9, 11],
       [17, 21, 13, 15]])

In [ ]:
np.cumsum(a).reshape(4,4)

In [ ]:
#Matrix Multiplication

"""Either nrows of matrix 1 should be equal to ncols of matrix 2 OR
nrows of matrix 2 should be equal to ncols of matrix 1"""

a = np.arange(0,15).reshape(3,5)
b = np.arange(0,15).reshape(5,3)
print(a)
print(b)
a.dot(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

In [ ]:
a=np.random.randint(0,10,15).reshape(3,5)
b=np.random.randint(0,10,15).reshape(3,5)
print(a)
print(b)
a*b

[[6 3 6 8 3]
 [0 0 0 3 3]
 [9 6 9 4 3]]
[[1 1 3 6 8]
 [2 4 2 4 1]
 [7 6 9 3 1]]


array([[ 6,  3, 18, 48, 24],
       [ 0,  0,  0, 12,  3],
       [63, 36, 81, 12,  3]])

In [ ]:
a = np.arange(0,15).reshape(3,5)
print(a)
print(a.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
np.set_printoptions(suppress=True)     #To avoid output in scientific format
a = np.arange(0,50.5,.5)
print(a)
np.cumsum(a)

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
a+b

In [ ]:
#What if we try to add arrays with different dimensions i.e. unequal number of rows/columns?
a=np.array([[1,5,3],[6,2,4],[7,8,9]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
a+b

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])

print(a)
print(b)
a-b

In [ ]:
print(a)
print(b)
a**b

In [ ]:
print(a)
print(b)
a*b

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
print(a*b)
print(np.dot(a,b))

In [ ]:
#Matrix Multiplication
a=np.array([[1,5],[6,2]])
b=np.array([[2,3],[2,3]])
c=np.array([2,3]).reshape(-1,1)
d=np.array([2,3])
print(a)
print(b)
print(c)
print(d)

np.dot(a,d)

In [ ]:
a=np.array([[1,5,4],[6,2,9]])
b=np.array([[2,3,1],[2,3,7]]).transpose()
print(a)
print(b)
np.dot(a,b)

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)
print(a.reshape(8,-1))
#print(a.reshape(-1,1))

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
b = np.array([2,3,3,4])
a+b

In [ ]:
print(b)
print(a)
np.dot(b,a)

In [ ]:
print(a)
print(b)
a/b

In [ ]:
print(a)
print(b)

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)
a.reshape(-1,1)

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)
a.reshape(1,-1)

In [ ]:
#Horizontal Stack - Requires the arrays to have equal number of rows
import numpy as np
a=np.array([[2,6,9],[8,6,4]])
b=np.array([[9,5,6,4],[7,3,8,7]])
print(a)
print(b)
np.hstack((a,b))

[[2 6 9]
 [8 6 4]]
[[9 5 6 4]
 [7 3 8 7]]


array([[2, 6, 9, 9, 5, 6, 4],
       [8, 6, 4, 7, 3, 8, 7]])

In [ ]:
#Vertical Stack
#Not possible for arrays having unequal number of columns
np.vstack((a,b))

ValueError: ignored

In [ ]:
a=np.array([[1,5,3],[6,2,4],[1,2,4],[8,3,6]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
np.vstack((a,b))

[[1 5 3]
 [6 2 4]
 [1 2 4]
 [8 3 6]]
[[8 5 7]
 [4 3 1]]


array([[1, 5, 3],
       [6, 2, 4],
       [1, 2, 4],
       [8, 3, 6],
       [8, 5, 7],
       [4, 3, 1]])

For a vertical stack, i.e. placing the array elements of a & b one below the other, we must have equal number of columns in both the arrays to be stacked

For a horizontal stack, i.e. placing the array elements of a & b next to each other, we must have equal number of rows in both the arrays to be stacked

In [ ]:
np.hstack((a,b))

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,8,6],[4,3,7,9]])
print(a)
print(b)

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
a=np.array([[1,5,3,5],[6,2,4,6],[7,1,2,3]])
b=np.array([[8,5,8,6],[4,3,7,9]])
print(a)
print(b)

In [ ]:
np.hstack((a,b))

In [ ]:
np.vstack((a,b))

In [ ]:
np.arange(1,26)

In [ ]:
#Numbers starting from 1 to 25 arranged/reshaped in 5 rows & 5 columns
print(np.arange(0,26))
np.arange(1,26).reshape(5,5)

In [ ]:
array1=np.arange(15).reshape(3,5)
array1

In [ ]:
a=np.arange(15).reshape(5,3)
a

In [ ]:
print(a.reshape(-1,1))
print(a.reshape(1,-1))

In [ ]:
array1=np.arange(30).reshape(5,6)
array1

In [ ]:
array1[3][2]=14
array1

In [ ]:
a=np.array([[4,8,7,5,6,1,4,8,7,4]])
b=np.unique(a)
b

In [ ]:
a=np.array([[4,8,7,5,6],[1,4,8,7,4]])
a

In [ ]:
b=a.transpose()
b

In [ ]:
#Between 1 to 1000, find the multiples of 3 AND 7.
import numpy as np
list5=[]
for i in range(1,1001):
    if i%21==0:
        list5.append(i)
print(list5)
a=np.array(list5)
a
#--------------------------------#

list5=[]
for i in range(1,1001):
    if (i%3==0) & (i%7==0):
        list5.append(i)
print(list5)
a=np.array(list5)
a

In [ ]:
import numpy as np
a=np.array([2,5,4,6,7,8])
b=np.array([4,7,8,5,4,4])
print(a)
print(b)

In [ ]:
c=np.concatenate((a,b))
c

In [ ]:
c=np.concatenate((b,a))
c

In [ ]:
a=np.array([[2,5,4],[6,7,8]])
b=np.array([[4,7,8],[5,4,4]])

In [ ]:
print(a)
print(b)

In [ ]:
c=np.concatenate((a,b))
c

In [ ]:
help(np.allclose)

In [ ]:
import numpy as np
Array1=np.linspace(3,5,5)
print(Array1)
Array2=np.linspace(4,5,5)
print(Array2)
np.greater_equal(Array1,Array2)

In [ ]:
np.less_equal(Array1,Array2)

In [ ]:
np.equal(Array1,Array2)

In [ ]:
Array1=np.linspace(3,6,5)
print(Array1)
Array2=np.linspace(4,9,5)
print(Array2)
np.greater_equal(Array1,Array2)

In [ ]:
Array1=np.empty((3,2),dtype=int)
Array1

In [ ]:
Array1=np.ones((3,6),dtype=int)
Array1

In [ ]:
l=[1,5,7,5,5,7,4]
arr=np.asarray(l)
arr

In [ ]:
l=[1,5,[7,5],5,7,4]
arr=np.asarray(l)
arr

In [ ]:
type(arr)

In [ ]:
l=(4,7,8,5,1,4,6)
arr=np.asarray(l)
arr

In [ ]:
type(arr)

In [ ]:
Dict_1 = {d: "ABC", e : "DEF" , f: "GHI"}
Dict_1

In [ ]:
a=np.array([4,5,2,1,7,8,6,3,4,5])
b=np.array([8,5,4,1,3,9,8,5,2,1])
c=a*b
c

In [ ]:
d=a+b
d

In [ ]:
a=np.array([4,5,2,1,7,8,6,3,4])
b=np.array([8,5,4,1,3,9,8,5,2,1])
c=a+b
c

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[4,7,2,1]])
b=np.array([4,7,8,5])
c=a+b
c

In [ ]:
a=np.array([[1,2,3,5],[5,8,9,7],[8,2,4,6]])
a

In [ ]:
for x in np.nditer(a):
    print(x,end=' ')

In [ ]:
for x in np.nditer(a):
    print(x)

In [ ]:
print(a)

In [ ]:
# 'T' stands for transpose... It will change rows to columns & columns to rows.
trans_a=a.T
trans_a

In [ ]:
np.char.add(['Welcome','to'],['Python','Session'])

In [ ]:
np.add([2,3],[5,8])

In [ ]:
np.char.multiply("Hello",5)

In [ ]:
print(np.char.center('Python Session',30,'+'))
np.char.center('Python Session',30,'+')

In [ ]:
np.char.capitalize('welcome to python session')

In [ ]:
np.char.title('welcome to python session')

In [ ]:
np.char.upper('welcome to python session')

In [ ]:
np.char.lower('WELCOME TO PYTHON SESSION')

In [ ]:
np.char.split("Welcome to Python Session")

In [ ]:
print(np.char.splitlines("Welcome\nto\nPython\nSession"))

In [ ]:
print(np.char.strip("        Welcome\nto\nPython\nSession     "))

In [ ]:
print(np.char.join('-','HMNSGD'))

In [ ]:
s='Welcome to Python Session'
s

In [ ]:
import numpy as np

In [ ]:
print(s)
print(np.char.replace(s,"Welcome to ","www."))

In [ ]:
t='Hello Neha, welcome to the class'
print(t)
print(np.char.replace(t,"class","party"))

In [ ]:
arr = np.array([12.2021, 90.23120, 123.0203, 23.202])
np.around(arr, 2)

In [ ]:
arr=np.array([12.45158,45.786546,7.8415868,5.486,4.8])
np.around(arr,3)

In [ ]:
np.floor(arr)

In [ ]:
np.ceil(arr)

In [ ]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])
np.amin(a)
np.amin(a)
np.amin(a,0)
np.amax(a,0)
np.amin(a,1)
np.amax(a,1)

In [ ]:
a=np.array([[2,10,20],[80,43,31],[22,43,10]])
a

In [ ]:
np.amax(a,1)

In [ ]:
np.ptp(a,1)
np.ptp(a,0)


In [ ]:
#Peak to peak

In [ ]:
a

In [ ]:
np.ptp(a,1)

In [ ]:
a=np.array([[1,4],[5,3]])
a

In [ ]:
np.sum(a,axis=1)

In [ ]:
a=np.random.rand(5,2)
a

In [ ]:
a=np.random.randint(5, size=(5,6))
a

In [ ]:
np.array([1.+0.j, 2.+0.j, 3.+0.j],dtype=float)

In [ ]:
np.mat(np.array([1,2,3,4]))

In [ ]:
np.mat(np.array([[1,4,5],[7,8,9]]))

In [ ]:
np.mat('1 2;3 4;8 9')

In [ ]:
a=[7,4,5,6,9]
type(a)

In [ ]:
type(np.asarray(a))

In [ ]:
type(a)

In [ ]:
issubclass(np.matrix,np.ndarray)

In [ ]:
issubclass(np.ndarray,np.matrix)

In [ ]:
a=[1,2,3]
type(a)

In [ ]:
np.asanyarray(a)

In [ ]:
a=np.matrix([1,2,3,4])
a

In [ ]:
np.asanyarray(a)

In [ ]:
x=np.array([1,2,3])
x

In [ ]:
y=x

In [ ]:
y

In [ ]:
y[1]=45

In [ ]:
y

In [ ]:
x

In [ ]:
x[0]=89
x

In [ ]:
y

In [ ]:
x=[1,2,3]
x

In [ ]:
z=np.copy(x)
z

In [ ]:
x[2]=8435486
x

In [ ]:
z

In [ ]:
z[2]=89
z

In [ ]:
x

In [ ]:
np.fromfunction(lambda i,j: i==j,(3,3),dtype=int)

In [ ]:
i=np.mat(np.array([[0,0,0],[1,1,1],[2,2,2]]))
i

In [ ]:
j=np.mat(np.array([[0,1,2],[0,1,2],[0,1,2]]))
j

In [ ]:
print(i)
print(j)
k=np.array([['00','01','02'],['10','11','12'],['20','21','22']])
print(k)

In [ ]:
np.fromfunction(lambda i,j: i*j,(3,3),dtype=int)

In [ ]:
np.fromfunction(lambda i,j,k: i*j*k,(3,3,3),dtype=int)

In [ ]:
list(range(5))
iterable=(x*x for x in range(5))

In [ ]:
iterable

In [ ]:
np.fromiter(iterable,float)

In [ ]:
list(range(5))

Create a list of a few temperature values in celcius (between 30 to 45 degrees)
Using 'for' loop, create another list where the celcius temperatures are converted into fahrenheit.

C*(9/5)+32=F

After converting to fahrenheit, create a dataframe with one column showing the above temperatures in celcius,and the nect column showing fahrenheit values for the given temperatures.

In [ ]:
import numpy as np
import pandas as pd
C=np.arange(30,45,2)
print(C)
F=[]
for i in (C,F):
    F=C*(9/5)+32

print(F)

TEMPERATURE={"C":C, "F":F}
result=pd.DataFrame(TEMPERATURE)
result

In [ ]:
import pandas as pd
import numpy as np
import random
df = pd.DataFrame(columns=['C','F'])
x=list(np.random.randint(30,45, size=(5)))
y=[]
for i in x:
    f=i*(9/5)+32
    y.append(f)
df['C']=pd.Series(x)
df['F']=pd.Series(y)
df

In [ ]:
a=np.random.randint(2,40,size=(5))
print(a)
b=np.linspace(6,9,2)
print(b)
np.less_equal(a,b)

In [ ]:
import numpy as np
a=np.arange(1,11)
print(a)
b=a.reshape(10,1)
print(b)
for i in a:
    c=np.power(a,b)
print(c)